import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'generated/l10n.dart';
import 'screens/home.dart';
import 'screens/qr.dart'; // Assuming this file is generated by the Flutter Intl extension

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: [
        S.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: S.delegate.supportedLocales,
      builder: (BuildContext context, Widget? child) {
        // Set text direction to RTL globally
        return Directionality(
          textDirection: TextDirection.rtl,
          child: child!,
        );
      },
      home: QRViewExample(),
    );
  }
}
